name: risk_engine make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    
    - name: build
      run: go build ./cmd/risk_engine/engine.go

